### ISSUE TITLE
Nuevo cliente MD

### ISSUE THREAD

**Issue by alberto-ln** [TheCookiesAgency/fileseeder#5]
Crear los archivos en base a un fichero md, la estructura sera la siguiente, el fichero se llaramra structure.md y estara en raiz
# **page**
# template
### molecule

- **Page** simulara create:gatsby-page, create:landing y create:sanity-document
- **Template** lo mismo que lo anterios pero en lugar de create:gatsby-page, hacer esto, create:gatsby-template 
- **Organism** ejecutara  create:organism y create:sanity-object
- **molecule** ejecutara create:molecule

Sí ya existe algo avisar de que existe y no reemplazar nada pero continuar.
Cuidado con el index. En sanity tiene su propia responsabilidad, allí habrá que renombrarlo con home

Añadir un flag --force si queremos reemplazar lo existente

**Comment by Raulacinherrero** [comment]
hecho
